services:
  auth:
    image: docs/auth:latest
    build: auth
    ports:
      - "8000:8000"
    volumes:
      - "./auth:/app"
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    environment:
      - POSTGRES_PASSWORD
      - REDIS_URI
      - DOCS_SECRET

  api:
    image: docs/api:latest
    build: api
    ports:
      - "4567:4567"
    volumes:
      - "./api:/app"
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    environment:
      - WEB_CONCURRENCY=2
      - REDIS_URI
      - DOCS_SECRET
      # APP_ENV: production

  pg:
    image: postgres:15.3
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    environment:
      - POSTGRES_PASSWORD

  redis:
    image: redis:7.0.12
    volumes:
      - "redis-data:/data"
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning

  # web:
  #   image: nginx

volumes:
  pg-data: {}
  redis-data: {}
