version: "3.7"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logrotate.conf:/etc/logrotate.d/nginx
      - ./webapp:/var/www/webapp
      - ./webapp/logs:/var/log/nginx
    depends_on:
      - app
  app:
    build: webapp/server
    restart: unless-stopped
    environment:
      ENV: "PROD"
    volumes:
      - ./webapp/logs:/app/logs
    depends_on:
      - redis
    networks:
      - internal

  redis:
    image: redis:7.2.0-alpine
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  redis-data: {}
