version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8080:8080
    networks:
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/var/www/webapp
      - ./webapp/logs:/var/log/nginx
    depends_on:
      - flask
  flask:
    build: webapp/server
    environment:
      ENV: "PROD"
    volumes:
      - ./webapp/logs:/flask/logs
    depends_on:
      - redis
    networks:
      - internal
    restart: always

  redis:
    image: redis
    networks:
      - internal

volumes:
  data:

networks:
  internal:
    driver: bridge
